# Generated by Django 3.1 on 2020-09-02 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MoneyTransfer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enter_your_email', models.CharField(default=None, max_length=150)),
                ('enter_the_destination_account_number', models.IntegerField()),
                ('enter_the_amount_to_be_transferred_in_KSHS', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_number', models.IntegerField()),
                ('balance', models.IntegerField(default=0)),
                ('email', models.CharField(default=None, max_length=150)),
            ],
        ),
    ]
