# Generated by Django 3.1 on 2020-09-02 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='moneytransfer',
            old_name='enter_your_email',
            new_name='enter_your_user_name',
        ),
        migrations.RenameField(
            model_name='status',
            old_name='email',
            new_name='user_name',
        ),
        migrations.AlterField(
            model_name='status',
            name='balance',
            field=models.IntegerField(),
        ),
    ]
