# Generated by Django 3.1 on 2020-09-02 15:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20200902_1342'),
    ]

    operations = [
        migrations.RenameField(
            model_name='moneytransfer',
            old_name='enter_the_amount_to_be_transferred_in_KSHS',
            new_name='enter_the_amount_to_be_transferred_in_USD',
        ),
    ]
