# Generated by Django 3.1 on 2020-09-03 00:52

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20200902_1814'),
    ]

    operations = [
        migrations.AddField(
            model_name='moneytransfer',
            name='created_on',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2020, 9, 3, 3, 52, 34, 474609)),
            preserve_default=False,
        ),
    ]
