# Generated by Django 3.1 on 2020-10-27 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_wallethistory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wallethistory',
            name='receiver',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='wallethistory',
            name='sender',
            field=models.CharField(max_length=200),
        ),
    ]
