# Generated by Django 3.1 on 2020-09-02 05:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20200901_2031'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='verified',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='Verification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('national_id', models.PositiveIntegerField(unique=True)),
                ('front_id', models.ImageField(upload_to='Id_Pics')),
                ('back_id', models.ImageField(upload_to='Id_Pics')),
                ('proof', models.ImageField(upload_to='Id_Pics')),
                ('is_verified', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='verified_users', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
