# Generated by Django 3.1 on 2020-09-02 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_auto_20200902_0848'),
    ]

    operations = [
        migrations.RenameField(
            model_name='verification',
            old_name='back_id',
            new_name='back_Id',
        ),
        migrations.RenameField(
            model_name='verification',
            old_name='front_id',
            new_name='front_Id',
        ),
        migrations.RenameField(
            model_name='verification',
            old_name='national_id',
            new_name='national_Id',
        ),
        migrations.AlterField(
            model_name='user',
            name='mobile',
            field=models.PositiveIntegerField(blank=True, null=True, unique=True),
        ),
    ]
