# Generated by Django 3.1 on 2020-09-03 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_auto_20200902_1248'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='profile_pic',
            field=models.ImageField(blank=True, default='default/blank.png', null=True, upload_to='users/%Y/%m/%d'),
        ),
    ]
