# Generated by Django 3.1 on 2020-09-05 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_auto_20200903_0818'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_investor',
            field=models.BooleanField(default=False),
        ),
    ]
