# Generated by Django 3.1 on 2020-09-05 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investors', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='investment',
            old_name='product',
            new_name='product_1',
        ),
        migrations.AddField(
            model_name='investment',
            name='product_2',
            field=models.CharField(blank=True, help_text='Second Product', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='investment',
            name='product_3',
            field=models.CharField(blank=True, help_text='Third Product', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='investment',
            name='product_4',
            field=models.CharField(blank=True, help_text='Fourth Product', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='investment',
            name='product_5',
            field=models.CharField(blank=True, help_text='Fifth Product', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='investment',
            name='dividend',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
