# Generated by Django 3.1 on 2020-09-05 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investors', '0002_auto_20200905_1856'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='investment',
            name='product_1',
        ),
        migrations.AddField(
            model_name='investment',
            name='product',
            field=models.CharField(default=1, help_text='First Product', max_length=200),
            preserve_default=False,
        ),
    ]
