# Generated by Django 3.1 on 2020-09-06 02:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0012_auto_20200905_1358'),
        ('investors', '0003_auto_20200905_1857'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='investment',
            name='product_2',
        ),
        migrations.RemoveField(
            model_name='investment',
            name='product_3',
        ),
        migrations.RemoveField(
            model_name='investment',
            name='product_4',
        ),
        migrations.RemoveField(
            model_name='investment',
            name='product_5',
        ),
        migrations.AddField(
            model_name='investment',
            name='category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='loans.category'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='investment',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='loans.product'),
        ),
    ]
