# Generated by Django 3.1 on 2020-09-07 05:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('investors', '0005_payment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='investment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='investors.investment'),
        ),
    ]
