# Generated by Django 3.1 on 2020-09-07 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investors', '0007_schema'),
    ]

    operations = [
        migrations.AddField(
            model_name='schema',
            name='time',
            field=models.CharField(choices=[('Daily', 'Daily'), ('Weekly', 'Weekly'), ('Monthly', 'Monthly'), ('Semi_Annualy', 'Semi_Annualy'), ('Annualy', 'Annualy')], default='Monthly', max_length=50),
        ),
    ]
