# Generated by Django 3.1 on 2020-09-04 07:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='commodity',
            options={'ordering': ('name',), 'verbose_name_plural': 'Commodities'},
        ),
    ]
