# Generated by Django 3.1 on 2020-10-07 06:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='loan',
            name='category',
        ),
    ]
