# Generated by Django 3.1 on 2020-09-04 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0002_auto_20200904_1052'),
    ]

    operations = [
        migrations.AddField(
            model_name='commodity',
            name='period',
            field=models.IntegerField(default=3),
            preserve_default=False,
        ),
    ]
