# Generated by Django 3.1 on 2020-09-05 01:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0004_customer_order_orderitem_shippingaddress'),
    ]

    operations = [
        migrations.AddField(
            model_name='commodity',
            name='digital',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
