# Generated by Django 3.1 on 2020-09-05 02:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0006_auto_20200905_0456'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Commodity',
            new_name='Product',
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ('name',)},
        ),
        migrations.RenameField(
            model_name='orderitem',
            old_name='commodity',
            new_name='product',
        ),
    ]
