# Generated by Django 3.1 on 2020-09-05 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0008_loan'),
    ]

    operations = [
        migrations.AddField(
            model_name='loan',
            name='address',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='loan',
            name='installment',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='loan',
            name='months',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
