# Generated by Django 3.1 on 2020-09-05 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0009_auto_20200905_1220'),
    ]

    operations = [
        migrations.AddField(
            model_name='loan',
            name='phone',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
