# Generated by Django 3.1 on 2020-09-05 10:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0011_auto_20200905_1357'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loan',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='loans.category'),
        ),
    ]
