# Generated by Django 3.1 on 2020-09-29 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0012_auto_20200905_1358'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loan',
            name='phone',
            field=models.CharField(max_length=20),
        ),
    ]
