# Generated by Django 3.1 on 2020-09-08 12:43

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('num_of_members', models.IntegerField()),
                ('cum_amount', models.IntegerField()),
                ('contrib_amount', models.IntegerField()),
                ('num_of_days_per_turn', models.IntegerField()),
                ('group_id', models.IntegerField(unique=True)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('end_date', models.DateTimeField()),
                ('members', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
