# Generated by Django 3.1 on 2020-10-24 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adashi', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='join',
            name='spinned',
            field=models.BooleanField(default=False),
        ),
    ]
