# Generated by Django 3.1 on 2020-09-29 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adashi', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='join',
            name='spinned',
        ),
        migrations.RemoveField(
            model_name='join',
            name='spinner_position',
        ),
        migrations.AddField(
            model_name='join',
            name='approved',
            field=models.BooleanField(default=False),
        ),
    ]
