# Generated by Django 3.1 on 2020-09-09 03:44

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('adashi', '0002_auto_20200908_1951'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='members',
            field=models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL),
        ),
    ]
