# Generated by Django 3.1 on 2020-09-16 16:06

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('adashi', '0005_auto_20200914_0622'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Category',
            new_name='AdashiGroup',
        ),
    ]
