# Generated by Django 3.1 on 2020-09-18 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adashi', '0007_calendar'),
    ]

    operations = [
        migrations.AddField(
            model_name='calendar',
            name='d_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
